/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { SpecialPlayer } from "./SpecialPlayer";
import { SpecialPlayerCountArgs } from "./SpecialPlayerCountArgs";
import { SpecialPlayerFindManyArgs } from "./SpecialPlayerFindManyArgs";
import { SpecialPlayerFindUniqueArgs } from "./SpecialPlayerFindUniqueArgs";
import { CreateSpecialPlayerArgs } from "./CreateSpecialPlayerArgs";
import { UpdateSpecialPlayerArgs } from "./UpdateSpecialPlayerArgs";
import { DeleteSpecialPlayerArgs } from "./DeleteSpecialPlayerArgs";
import { ScoreFindManyArgs } from "../../score/base/ScoreFindManyArgs";
import { Score } from "../../score/base/Score";
import { SpecialPlayerService } from "../specialPlayer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SpecialPlayer)
export class SpecialPlayerResolverBase {
  constructor(
    protected readonly service: SpecialPlayerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "read",
    possession: "any",
  })
  async _specialPlayersMeta(
    @graphql.Args() args: SpecialPlayerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SpecialPlayer])
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "read",
    possession: "any",
  })
  async specialPlayers(
    @graphql.Args() args: SpecialPlayerFindManyArgs
  ): Promise<SpecialPlayer[]> {
    return this.service.specialPlayers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SpecialPlayer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "read",
    possession: "own",
  })
  async specialPlayer(
    @graphql.Args() args: SpecialPlayerFindUniqueArgs
  ): Promise<SpecialPlayer | null> {
    const result = await this.service.specialPlayer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SpecialPlayer)
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "create",
    possession: "any",
  })
  async createSpecialPlayer(
    @graphql.Args() args: CreateSpecialPlayerArgs
  ): Promise<SpecialPlayer> {
    return await this.service.createSpecialPlayer({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SpecialPlayer)
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "update",
    possession: "any",
  })
  async updateSpecialPlayer(
    @graphql.Args() args: UpdateSpecialPlayerArgs
  ): Promise<SpecialPlayer | null> {
    try {
      return await this.service.updateSpecialPlayer({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SpecialPlayer)
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "delete",
    possession: "any",
  })
  async deleteSpecialPlayer(
    @graphql.Args() args: DeleteSpecialPlayerArgs
  ): Promise<SpecialPlayer | null> {
    try {
      return await this.service.deleteSpecialPlayer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Score], { name: "scores" })
  @nestAccessControl.UseRoles({
    resource: "Score",
    action: "read",
    possession: "any",
  })
  async findScores(
    @graphql.Parent() parent: SpecialPlayer,
    @graphql.Args() args: ScoreFindManyArgs
  ): Promise<Score[]> {
    const results = await this.service.findScores(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
