/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SpecialPlayerService } from "../specialPlayer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SpecialPlayerCreateInput } from "./SpecialPlayerCreateInput";
import { SpecialPlayer } from "./SpecialPlayer";
import { SpecialPlayerFindManyArgs } from "./SpecialPlayerFindManyArgs";
import { SpecialPlayerWhereUniqueInput } from "./SpecialPlayerWhereUniqueInput";
import { SpecialPlayerUpdateInput } from "./SpecialPlayerUpdateInput";
import { ScoreFindManyArgs } from "../../score/base/ScoreFindManyArgs";
import { Score } from "../../score/base/Score";
import { ScoreWhereUniqueInput } from "../../score/base/ScoreWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SpecialPlayerControllerBase {
  constructor(
    protected readonly service: SpecialPlayerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SpecialPlayer })
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSpecialPlayer(
    @common.Body() data: SpecialPlayerCreateInput
  ): Promise<SpecialPlayer> {
    return await this.service.createSpecialPlayer({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        points: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SpecialPlayer] })
  @ApiNestedQuery(SpecialPlayerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async specialPlayers(
    @common.Req() request: Request
  ): Promise<SpecialPlayer[]> {
    const args = plainToClass(SpecialPlayerFindManyArgs, request.query);
    return this.service.specialPlayers({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        points: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SpecialPlayer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async specialPlayer(
    @common.Param() params: SpecialPlayerWhereUniqueInput
  ): Promise<SpecialPlayer | null> {
    const result = await this.service.specialPlayer({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        points: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SpecialPlayer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSpecialPlayer(
    @common.Param() params: SpecialPlayerWhereUniqueInput,
    @common.Body() data: SpecialPlayerUpdateInput
  ): Promise<SpecialPlayer | null> {
    try {
      return await this.service.updateSpecialPlayer({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          points: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SpecialPlayer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSpecialPlayer(
    @common.Param() params: SpecialPlayerWhereUniqueInput
  ): Promise<SpecialPlayer | null> {
    try {
      return await this.service.deleteSpecialPlayer({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          points: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/scores")
  @ApiNestedQuery(ScoreFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Score",
    action: "read",
    possession: "any",
  })
  async findScores(
    @common.Req() request: Request,
    @common.Param() params: SpecialPlayerWhereUniqueInput
  ): Promise<Score[]> {
    const query = plainToClass(ScoreFindManyArgs, request.query);
    const results = await this.service.findScores(params.id, {
      ...query,
      select: {
        createdAt: true,

        gameRound: {
          select: {
            id: true,
          },
        },

        id: true,

        player: {
          select: {
            id: true,
          },
        },

        playerPoints: true,

        specialPlayer: {
          select: {
            id: true,
          },
        },

        specialPlayerPoints: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/scores")
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "update",
    possession: "any",
  })
  async connectScores(
    @common.Param() params: SpecialPlayerWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        connect: body,
      },
    };
    await this.service.updateSpecialPlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/scores")
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "update",
    possession: "any",
  })
  async updateScores(
    @common.Param() params: SpecialPlayerWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        set: body,
      },
    };
    await this.service.updateSpecialPlayer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/scores")
  @nestAccessControl.UseRoles({
    resource: "SpecialPlayer",
    action: "update",
    possession: "any",
  })
  async disconnectScores(
    @common.Param() params: SpecialPlayerWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        disconnect: body,
      },
    };
    await this.service.updateSpecialPlayer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
