/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SpecialPlayer as PrismaSpecialPlayer,
  Score as PrismaScore,
} from "@prisma/client";

export class SpecialPlayerServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SpecialPlayerCountArgs, "select">
  ): Promise<number> {
    return this.prisma.specialPlayer.count(args);
  }

  async specialPlayers(
    args: Prisma.SpecialPlayerFindManyArgs
  ): Promise<PrismaSpecialPlayer[]> {
    return this.prisma.specialPlayer.findMany(args);
  }
  async specialPlayer(
    args: Prisma.SpecialPlayerFindUniqueArgs
  ): Promise<PrismaSpecialPlayer | null> {
    return this.prisma.specialPlayer.findUnique(args);
  }
  async createSpecialPlayer(
    args: Prisma.SpecialPlayerCreateArgs
  ): Promise<PrismaSpecialPlayer> {
    return this.prisma.specialPlayer.create(args);
  }
  async updateSpecialPlayer(
    args: Prisma.SpecialPlayerUpdateArgs
  ): Promise<PrismaSpecialPlayer> {
    return this.prisma.specialPlayer.update(args);
  }
  async deleteSpecialPlayer(
    args: Prisma.SpecialPlayerDeleteArgs
  ): Promise<PrismaSpecialPlayer> {
    return this.prisma.specialPlayer.delete(args);
  }

  async findScores(
    parentId: string,
    args: Prisma.ScoreFindManyArgs
  ): Promise<PrismaScore[]> {
    return this.prisma.specialPlayer
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .scores(args);
  }
}
