/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  GameRound as PrismaGameRound,
  Score as PrismaScore,
} from "@prisma/client";

export class GameRoundServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.GameRoundCountArgs, "select">
  ): Promise<number> {
    return this.prisma.gameRound.count(args);
  }

  async gameRounds(
    args: Prisma.GameRoundFindManyArgs
  ): Promise<PrismaGameRound[]> {
    return this.prisma.gameRound.findMany(args);
  }
  async gameRound(
    args: Prisma.GameRoundFindUniqueArgs
  ): Promise<PrismaGameRound | null> {
    return this.prisma.gameRound.findUnique(args);
  }
  async createGameRound(
    args: Prisma.GameRoundCreateArgs
  ): Promise<PrismaGameRound> {
    return this.prisma.gameRound.create(args);
  }
  async updateGameRound(
    args: Prisma.GameRoundUpdateArgs
  ): Promise<PrismaGameRound> {
    return this.prisma.gameRound.update(args);
  }
  async deleteGameRound(
    args: Prisma.GameRoundDeleteArgs
  ): Promise<PrismaGameRound> {
    return this.prisma.gameRound.delete(args);
  }

  async findScores(
    parentId: string,
    args: Prisma.ScoreFindManyArgs
  ): Promise<PrismaScore[]> {
    return this.prisma.gameRound
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .scores(args);
  }
}
