/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { GameRound } from "./GameRound";
import { GameRoundCountArgs } from "./GameRoundCountArgs";
import { GameRoundFindManyArgs } from "./GameRoundFindManyArgs";
import { GameRoundFindUniqueArgs } from "./GameRoundFindUniqueArgs";
import { CreateGameRoundArgs } from "./CreateGameRoundArgs";
import { UpdateGameRoundArgs } from "./UpdateGameRoundArgs";
import { DeleteGameRoundArgs } from "./DeleteGameRoundArgs";
import { ScoreFindManyArgs } from "../../score/base/ScoreFindManyArgs";
import { Score } from "../../score/base/Score";
import { GameRoundService } from "../gameRound.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => GameRound)
export class GameRoundResolverBase {
  constructor(
    protected readonly service: GameRoundService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GameRound",
    action: "read",
    possession: "any",
  })
  async _gameRoundsMeta(
    @graphql.Args() args: GameRoundCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [GameRound])
  @nestAccessControl.UseRoles({
    resource: "GameRound",
    action: "read",
    possession: "any",
  })
  async gameRounds(
    @graphql.Args() args: GameRoundFindManyArgs
  ): Promise<GameRound[]> {
    return this.service.gameRounds(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => GameRound, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GameRound",
    action: "read",
    possession: "own",
  })
  async gameRound(
    @graphql.Args() args: GameRoundFindUniqueArgs
  ): Promise<GameRound | null> {
    const result = await this.service.gameRound(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => GameRound)
  @nestAccessControl.UseRoles({
    resource: "GameRound",
    action: "create",
    possession: "any",
  })
  async createGameRound(
    @graphql.Args() args: CreateGameRoundArgs
  ): Promise<GameRound> {
    return await this.service.createGameRound({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => GameRound)
  @nestAccessControl.UseRoles({
    resource: "GameRound",
    action: "update",
    possession: "any",
  })
  async updateGameRound(
    @graphql.Args() args: UpdateGameRoundArgs
  ): Promise<GameRound | null> {
    try {
      return await this.service.updateGameRound({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GameRound)
  @nestAccessControl.UseRoles({
    resource: "GameRound",
    action: "delete",
    possession: "any",
  })
  async deleteGameRound(
    @graphql.Args() args: DeleteGameRoundArgs
  ): Promise<GameRound | null> {
    try {
      return await this.service.deleteGameRound(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Score], { name: "scores" })
  @nestAccessControl.UseRoles({
    resource: "Score",
    action: "read",
    possession: "any",
  })
  async findScores(
    @graphql.Parent() parent: GameRound,
    @graphql.Args() args: ScoreFindManyArgs
  ): Promise<Score[]> {
    const results = await this.service.findScores(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
