/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { GameRoundWhereUniqueInput } from "../../gameRound/base/GameRoundWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { PlayerWhereUniqueInput } from "../../player/base/PlayerWhereUniqueInput";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { SpecialPlayerWhereUniqueInput } from "../../specialPlayer/base/SpecialPlayerWhereUniqueInput";

@InputType()
class ScoreWhereInput {
  @ApiProperty({
    required: false,
    type: () => GameRoundWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GameRoundWhereUniqueInput)
  @IsOptional()
  @Field(() => GameRoundWhereUniqueInput, {
    nullable: true,
  })
  gameRound?: GameRoundWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => PlayerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PlayerWhereUniqueInput)
  @IsOptional()
  @Field(() => PlayerWhereUniqueInput, {
    nullable: true,
  })
  player?: PlayerWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  playerPoints?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SpecialPlayerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SpecialPlayerWhereUniqueInput)
  @IsOptional()
  @Field(() => SpecialPlayerWhereUniqueInput, {
    nullable: true,
  })
  specialPlayer?: SpecialPlayerWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  specialPlayerPoints?: FloatNullableFilter;
}

export { ScoreWhereInput as ScoreWhereInput };
