/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  ValidateNested,
  IsOptional,
  IsString,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { GameRound } from "../../gameRound/base/GameRound";
import { Player } from "../../player/base/Player";
import { SpecialPlayer } from "../../specialPlayer/base/SpecialPlayer";

@ObjectType()
class Score {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => GameRound,
  })
  @ValidateNested()
  @Type(() => GameRound)
  @IsOptional()
  gameRound?: GameRound | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => Player,
  })
  @ValidateNested()
  @Type(() => Player)
  @IsOptional()
  player?: Player | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  playerPoints!: number | null;

  @ApiProperty({
    required: false,
    type: () => SpecialPlayer,
  })
  @ValidateNested()
  @Type(() => SpecialPlayer)
  @IsOptional()
  specialPlayer?: SpecialPlayer | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  specialPlayerPoints!: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Score as Score };
